### ISSUE TITLE
Пользователи (customers)

### ISSUE THREAD

**Issue by temanaganov** [ilantipov/hackathon#33]
- [x] Не работает удаление пользователя
- [x] При создании / редактировании пользователя мы остаемся на той же странице.
- [x] При заходе на страницу редактирования, или после ее перезагрузки поле Email всегда остается пустым

**Comment by nikitaMai** [comment]
Беру задачу себе

**Comment by nikitaMai** [comment]
После создания пользователя сделал редирект на страницу всех customers
Сделал удаление пользователя
