### ISSUE TITLE
Swift_TransportException: Cannot send message without a sender address in file 

### ISSUE THREAD

**Issue by ilantipov** [ilantipov/hackathon#44]
Ошибка отправке тестового письма при бронировании

**Comment by smilelanss** [comment]
в .env прописать доступы к тестовому почтовому ящику, к примеру
```
MAIL_MAILER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=e05f23a2a49281
MAIL_PASSWORD=e382bcbc714ac7
MAIL_ENCRYPTION=tls
```

**Comment by nikitaMai** [comment]
Так же нужно указать e-mail с которого будет отправляться письмо (Для mailtrap он может быть любой)
`MAIL_FROM_ADDRESS=rooms@involta.ru`

**Comment by ilantipov** [comment]
Внес изменения в обеих тестовых комнатах
