### ISSUE TITLE
Связать интерфейс с другими комнатами

### ISSUE THREAD

**Issue by ilantipov** [ilantipov/hackathon#56]
Сделать снизу вывод каруселью инфу по занятости других комнат.

- [x] Сделать снизу вывод каруселью инфу по занятости других комнат. 
- [x] При клике на комнату менять вызовы по апи на урл той комнаты
- [x] Посе первого клика на комнату карусели перезагрузить страницу для выбранной комнаты

**Comment by IlyesAkb** [comment]
Добавил карусельку с комнатами
